public class Main {

    public static void main(String[] args) {
        System.out.println("Тестирование версии 1.0");
        TasksManager tasksManager = new TasksManager();
        Task task1 = tasksManager.createTask("Задача 1", "Описаиние задачи 1");
        System.out.println("Создали задачу 1");
        System.out.println(task1.getTitle());
        System.out.println(task1.getDescription());
        System.out.println(task1.getId());
        System.out.println(task1.getStatus());
        TasksManager.tasks.put(task1.getId(), task1);
        System.out.println("Сохранили задачу 1");
        tasksManager.updateTask(task1,"Сходить в магазин", "Молоко, Хлеб", "DONE");
        System.out.println("Изменили задачу 1");
        System.out.println(task1.getTitle());
        System.out.println(task1.getDescription());
        System.out.println(task1.getId());
        System.out.println(task1.getStatus());
        Task task2 = tasksManager.createTask("Задача 2", "Описаиние задачи 2");
        System.out.println("Создали задачу 2");
        TasksManager.tasks.put(task2.getId(), task2);
        System.out.println("Сохранили задачу 2");
        Task task3 = tasksManager.createTask("Задача 3", "Описаиние задачи 3");
        System.out.println("Создали задачу 3");
        TasksManager.tasks.put(task3.getId(), task3);
        System.out.println("Сохранили задачу 3");
        System.out.println(tasksManager.getAllTasks());
        System.out.println("Получили список всех задач");
        tasksManager.deleteTask(task2.getId());
        System.out.println("Удалили задачу 2");
        System.out.println(tasksManager.getAllTasks());
        System.out.println("Получили список всех задач");
        tasksManager.deleteAllTasks();
        System.out.println("Удалили все задачи");
        System.out.println(tasksManager.getAllTasks());
        System.out.println("Получили список всех задач");
        Epic epic1 = tasksManager.createEpic("Эпик 1", "Описание Эпика 1");
        System.out.println("Создали эпик 1");
        System.out.println(epic1.getTitle());
        System.out.println(epic1.getDescription());
        System.out.println(epic1.getId());
        System.out.println(epic1.getStatus());
        TasksManager.epics.put(epic1.getId(), epic1);
        System.out.println("Сохранили эпик 1");
        tasksManager.updateEpic(epic1, "Починить ноутбук", "Проблемы с питанием");
        System.out.println("Изменили эпик 1");
        System.out.println(epic1.getTitle());
        System.out.println(epic1.getDescription());
        System.out.println(epic1.getId());
        System.out.println(epic1.getStatus());
        System.out.println(tasksManager.getAllEpics());
        System.out.println("Получили список всех эпиков");
        Subtask subtask1 = tasksManager.createSubTask("Подзадача 1", "Описание подзадачи 1", epic1);
        System.out.println("Создали подзадачу 1");
        System.out.println(subtask1.getTitle());
        System.out.println(subtask1.getDescription());
        System.out.println(subtask1.getId());
        System.out.println(subtask1.getStatus());
        System.out.println(subtask1.getIdEpic());
        TasksManager.subtasks.put(subtask1.getId(), subtask1);
        System.out.println("Сохранили подзадачу 1");
        Subtask subtask2 = tasksManager.createSubTask("Подзадача 2", "Описание подзадачи 2", epic1);
        System.out.println("Создали подзадачу 2");
        System.out.println(subtask2.getTitle());
        System.out.println(subtask2.getDescription());
        System.out.println(subtask2.getId());
        System.out.println(subtask2.getStatus());
        System.out.println(subtask2.getIdEpic());
        TasksManager.subtasks.put(subtask2.getId(), subtask2);
        System.out.println("Сохранили подзадачу 2");
        Subtask subtask3 = tasksManager.createSubTask("Подзадача 3", "Описание подзадачи 3", epic1);
        System.out.println("Создали подзадачу 3");
        System.out.println(subtask3.getTitle());
        System.out.println(subtask3.getDescription());
        System.out.println(subtask3.getId());
        System.out.println(subtask3.getStatus());
        System.out.println(subtask3.getIdEpic());
        TasksManager.subtasks.put(subtask3.getId(), subtask3);
        System.out.println("Сохранили подзадачу 2");
        System.out.println(tasksManager.getAllSubtasks());
        System.out.println("Получили список всех подзадач");
        tasksManager.updateSubtask(subtask1, "Провести диагностику", "Описание диагностики", "DONE");
        System.out.println("Изменили подзадачу 1");
        System.out.println(subtask1.getTitle());
        System.out.println(subtask1.getDescription());
        System.out.println(subtask1.getId());
        System.out.println(subtask1.getStatus());
        System.out.println(subtask1.getIdEpic());
        System.out.println("Статус эпика 1: " + epic1.getStatus());
        tasksManager.updateSubtask(subtask2, "Купили коплектующие", "Аккумулятор, зарядка", "DONE");
        System.out.println("Изменили подзадачу 2");
        System.out.println(subtask2.getTitle());
        System.out.println(subtask2.getDescription());
        System.out.println(subtask2.getId());
        System.out.println(subtask2.getStatus());
        System.out.println(subtask2.getIdEpic());
        System.out.println("Статус эпика 1: " + epic1.getStatus());
        tasksManager.updateSubtask(subtask3, "Замена комплектующих", "Достать и засунть", "DONE");
        System.out.println("Изменили подзадачу 3");
        System.out.println(subtask3.getTitle());
        System.out.println(subtask3.getDescription());
        System.out.println(subtask3.getId());
        System.out.println(subtask3.getStatus());
        System.out.println(subtask3.getIdEpic());
        System.out.println("Статус эпика 1: " + epic1.getStatus());
        tasksManager.updateSubtask(subtask3, "Замена комплектующих", "Достать и засунть", "IN_PROGRESS");
        System.out.println("Изменили подзадачу 3");
        System.out.println(subtask3.getTitle());
        System.out.println(subtask3.getDescription());
        System.out.println(subtask3.getId());
        System.out.println(subtask3.getStatus());
        System.out.println(subtask3.getIdEpic());
        System.out.println("Статус эпика 1: " + epic1.getStatus());
        tasksManager.deleteSubtask(subtask3.getId());
        System.out.println("Удалили подзадачу 3");
        System.out.println("Статус эпика 1: " + epic1.getStatus());
        tasksManager.deleteEpic(epic1.getId());
        System.out.println("Удалили эпик 1");
        System.out.println(tasksManager.getAllEpics());
        System.out.println("Получили список всех эпиков");
        System.out.println(tasksManager.getAllSubtasks());
        System.out.println("Получили список всех подзадач");
        System.out.println("Тестирование успешно завершенно!");
    }
}
